### ISSUE TITLE
Inappropriate use of Mushroom Observer's API

### ISSUE THREAD

**Issue by mo-nathan** [senerdag/mushroomobserver-dataset#1]
From https://github.com/MushroomObserver/mushroom-observer/blob/main/README_API.md:

"Our API is intended for individual MO users to create and modify their and other users' MO Observations (and other objects) and for developing applications to support them. It is not intended for data scraping or for generalized experimentation with AI, image recognition or large data sets. For those purposes you should use the CSV files described below.

We're an all-volunteer organization with a tiny budget and scarce resources. Using the API to obtain large amounts of data puts an unnecessary strain on those resources and adversely impacts other users. If we notice improper usage of the API or usage that seriously impacts our performance we may institute blocks without notification."

Downloading the original images in particular is a VERY BAD THING.  We recently had a student use the script in this repository to scrape our entire Google Archive incurring very significant server costs by our organization.  We are now blocking access to the original image.  PLEASE DON'T ATTEMPT TO DOWNLOAD THE ORIGINAL IMAGES.  In our experience the 320 resolution images work very well for AI/ML.  We have compared the results with the 640 and 1280 images that are also available through our images server and there was essentially no difference in the resulting model and of course the processing time went up by a factor of 4x or 16x.

As stated in our README would be very happy to work with the authors of this site and other users who want access to the data to provide a more efficient and cost effective way to get you the data you want.

**Comment by senerdag** [comment]
I understand what you mean, I remember that I had previously informed that I would write such a repo and Some one in your crew was told that there was no problem. I can delete it if you want, of course there is no problem. I apologize for such a situation.

**Comment by mo-nathan** [comment]
Thanks for these updates!  Much appreciated.
